-- Core COBie sheet-compatible schema.
-- Field set is intentionally conservative; verify against the downloaded XLTX template before production hardening.

create table if not exists cobie.workbook (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references app.organizations(id) on delete cascade,
  name text not null,
  standard_version text not null default 'COBie UK 2.4',
  template_name text,
  template_source_url text,
  template_checksum text,
  ifc_schema text,
  status text not null default 'draft' check (status in ('draft', 'validated', 'locked', 'archived')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, name)
);

create trigger workbook_set_updated_at
before update on cobie.workbook
for each row execute function app.set_updated_at();

create index if not exists idx_workbook_org on cobie.workbook(organization_id);


create table if not exists cobie.contact (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references app.organizations(id) on delete cascade,
  workbook_id uuid not null references cobie.workbook(id) on delete cascade,
  email text,
  created_by_email text,
  created_on text,
  category text,
  company text,
  phone text,
  external_system text,
  external_object text,
  external_identifier text,
  department text,
  organization_code text,
  given_name text,
  family_name text,
  street text,
  postal_box text,
  town text,
  state_region text,
  postal_code text,
  country text,
  source_sheet text not null default 'Contact',
  source_row_number integer,
  raw_row jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workbook_id, email)
);

create table if not exists cobie.facility (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references app.organizations(id) on delete cascade,
  workbook_id uuid not null references cobie.workbook(id) on delete cascade,
  name text not null,
  created_by_email text,
  created_on text,
  category text,
  project_name text,
  site_name text,
  linear_units text,
  area_units text,
  volume_units text,
  currency_unit text,
  area_measurement text,
  external_system text,
  external_project_object text,
  external_project_identifier text,
  external_site_object text,
  external_site_identifier text,
  external_facility_object text,
  external_facility_identifier text,
  description text,
  project_description text,
  site_description text,
  phase text,
  source_sheet text not null default 'Facility',
  source_row_number integer,
  raw_row jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workbook_id, name)
);

create table if not exists cobie.floor (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references app.organizations(id) on delete cascade,
  workbook_id uuid not null references cobie.workbook(id) on delete cascade,
  name text not null,
  created_by_email text,
  created_on text,
  category text,
  external_system text,
  external_object text,
  external_identifier text,
  elevation text,
  height text,
  description text,
  source_sheet text not null default 'Floor',
  source_row_number integer,
  raw_row jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workbook_id, name)
);

create table if not exists cobie.space (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references app.organizations(id) on delete cascade,
  workbook_id uuid not null references cobie.workbook(id) on delete cascade,
  name text not null,
  created_by_email text,
  created_on text,
  category text,
  floor_name text,
  description text,
  external_system text,
  external_object text,
  external_identifier text,
  room_tag text,
  usable_height text,
  gross_area text,
  net_area text,
  source_sheet text not null default 'Space',
  source_row_number integer,
  raw_row jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workbook_id, name)
);

create table if not exists cobie.zone (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references app.organizations(id) on delete cascade,
  workbook_id uuid not null references cobie.workbook(id) on delete cascade,
  name text not null,
  created_by_email text,
  created_on text,
  category text,
  space_names text,
  external_system text,
  external_object text,
  external_identifier text,
  description text,
  source_sheet text not null default 'Zone',
  source_row_number integer,
  raw_row jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workbook_id, name)
);

create table if not exists cobie.type (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references app.organizations(id) on delete cascade,
  workbook_id uuid not null references cobie.workbook(id) on delete cascade,
  name text not null,
  created_by_email text,
  created_on text,
  category text,
  description text,
  asset_type text,
  manufacturer text,
  model_number text,
  warranty_guarantor_parts text,
  warranty_duration_parts text,
  warranty_guarantor_labor text,
  warranty_duration_labor text,
  warranty_duration_unit text,
  replacement_cost text,
  expected_life text,
  duration_unit text,
  warranty_description text,
  nominal_length text,
  nominal_width text,
  nominal_height text,
  model_reference text,
  shape text,
  size text,
  color text,
  finish text,
  grade text,
  material text,
  constituents text,
  features text,
  accessibility_performance text,
  code_performance text,
  sustainability_performance text,
  source_sheet text not null default 'Type',
  source_row_number integer,
  raw_row jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workbook_id, name)
);

create table if not exists cobie.component (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references app.organizations(id) on delete cascade,
  workbook_id uuid not null references cobie.workbook(id) on delete cascade,
  name text not null,
  created_by_email text,
  created_on text,
  type_name text,
  space_name text,
  description text,
  external_system text,
  external_object text,
  external_identifier text,
  serial_number text,
  installation_date text,
  warranty_start_date text,
  tag_number text,
  bar_code text,
  asset_identifier text,
  source_sheet text not null default 'Component',
  source_row_number integer,
  raw_row jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workbook_id, name)
);

create table if not exists cobie.system (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references app.organizations(id) on delete cascade,
  workbook_id uuid not null references cobie.workbook(id) on delete cascade,
  name text not null,
  created_by_email text,
  created_on text,
  category text,
  component_names text,
  external_system text,
  external_object text,
  external_identifier text,
  description text,
  source_sheet text not null default 'System',
  source_row_number integer,
  raw_row jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workbook_id, name)
);

create table if not exists cobie.assembly (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references app.organizations(id) on delete cascade,
  workbook_id uuid not null references cobie.workbook(id) on delete cascade,
  name text,
  created_by_email text,
  created_on text,
  sheet_name text,
  parent_name text,
  child_names text,
  assembly_type text,
  external_system text,
  external_object text,
  external_identifier text,
  description text,
  source_sheet text not null default 'Assembly',
  source_row_number integer,
  raw_row jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists cobie.connection (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references app.organizations(id) on delete cascade,
  workbook_id uuid not null references cobie.workbook(id) on delete cascade,
  name text,
  created_by_email text,
  created_on text,
  connection_type text,
  sheet_name text,
  row_name_1 text,
  row_name_2 text,
  realizing_element text,
  port_name_1 text,
  port_name_2 text,
  external_system text,
  external_object text,
  external_identifier text,
  description text,
  source_sheet text not null default 'Connection',
  source_row_number integer,
  raw_row jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists cobie.spare (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references app.organizations(id) on delete cascade,
  workbook_id uuid not null references cobie.workbook(id) on delete cascade,
  name text not null,
  created_by_email text,
  created_on text,
  category text,
  type_name text,
  suppliers text,
  external_system text,
  external_object text,
  external_identifier text,
  set_number text,
  part_number text,
  description text,
  source_sheet text not null default 'Spare',
  source_row_number integer,
  raw_row jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workbook_id, name)
);

create table if not exists cobie.resource (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references app.organizations(id) on delete cascade,
  workbook_id uuid not null references cobie.workbook(id) on delete cascade,
  name text not null,
  created_by_email text,
  created_on text,
  category text,
  external_system text,
  external_object text,
  external_identifier text,
  description text,
  source_sheet text not null default 'Resource',
  source_row_number integer,
  raw_row jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workbook_id, name)
);

create table if not exists cobie.job (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references app.organizations(id) on delete cascade,
  workbook_id uuid not null references cobie.workbook(id) on delete cascade,
  name text not null,
  created_by_email text,
  created_on text,
  category text,
  status text,
  type_name text,
  description text,
  duration text,
  duration_unit text,
  start_value text,
  task_start_unit text,
  frequency text,
  frequency_unit text,
  external_system text,
  external_object text,
  external_identifier text,
  task_number text,
  priors text,
  resource_names text,
  source_sheet text not null default 'Job',
  source_row_number integer,
  raw_row jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workbook_id, name)
);

create table if not exists cobie.impact (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references app.organizations(id) on delete cascade,
  workbook_id uuid not null references cobie.workbook(id) on delete cascade,
  name text,
  created_by_email text,
  created_on text,
  impact_type text,
  impact_stage text,
  sheet_name text,
  row_name text,
  value text,
  impact_unit text,
  lead_in_time text,
  duration text,
  lead_out_time text,
  external_system text,
  external_object text,
  external_identifier text,
  description text,
  source_sheet text not null default 'Impact',
  source_row_number integer,
  raw_row jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists cobie.document (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references app.organizations(id) on delete cascade,
  workbook_id uuid not null references cobie.workbook(id) on delete cascade,
  name text not null,
  created_by_email text,
  created_on text,
  category text,
  approval_by text,
  stage text,
  sheet_name text,
  row_name text,
  directory text,
  file text,
  external_system text,
  external_object text,
  external_identifier text,
  description text,
  reference text,
  source_sheet text not null default 'Document',
  source_row_number integer,
  raw_row jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workbook_id, name)
);

create table if not exists cobie.attribute (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references app.organizations(id) on delete cascade,
  workbook_id uuid not null references cobie.workbook(id) on delete cascade,
  name text not null,
  created_by_email text,
  created_on text,
  category text,
  sheet_name text,
  row_name text,
  value text,
  unit text,
  external_system text,
  external_object text,
  external_identifier text,
  description text,
  allowed_values text,
  source_sheet text not null default 'Attribute',
  source_row_number integer,
  raw_row jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists cobie.coordinate (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references app.organizations(id) on delete cascade,
  workbook_id uuid not null references cobie.workbook(id) on delete cascade,
  name text,
  created_by_email text,
  created_on text,
  category text,
  sheet_name text,
  row_name text,
  coordinate_x_axis text,
  coordinate_y_axis text,
  coordinate_z_axis text,
  ext_system text,
  ext_object text,
  ext_identifier text,
  clockwise_rotation text,
  elevational_rotation text,
  yaw_rotation text,
  source_sheet text not null default 'Coordinate',
  source_row_number integer,
  raw_row jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists cobie.issue (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references app.organizations(id) on delete cascade,
  workbook_id uuid not null references cobie.workbook(id) on delete cascade,
  name text not null,
  created_by_email text,
  created_on text,
  type text,
  risk text,
  chance text,
  impact text,
  sheet_name text,
  row_name text,
  description text,
  owner text,
  mitigation text,
  ext_system text,
  ext_object text,
  ext_identifier text,
  source_sheet text not null default 'Issue',
  source_row_number integer,
  raw_row jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (workbook_id, name)
);

create table if not exists cobie.picklist (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid references app.organizations(id) on delete cascade,
  workbook_id uuid references cobie.workbook(id) on delete cascade,
  sheet_name text not null,
  field_name text not null,
  value text not null,
  description text,
  source_version text,
  raw_row jsonb not null default '{}'::jsonb,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


do $$
declare
  t text;
begin
  foreach t in array array[
    'contact','facility','floor','space','zone','type','component','system','assembly','connection',
    'spare','resource','job','impact','document','attribute','coordinate','issue','picklist'
  ]
  loop
    execute format('drop trigger if exists %I_set_updated_at on cobie.%I', t, t);
    execute format('create trigger %I_set_updated_at before update on cobie.%I for each row execute function app.set_updated_at()', t, t);
  end loop;
end $$;
